core/categorias/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from core.categorias.views import *

app_name = 'categorias'

urlpatterns = [
    path('', login_required(CategoriaListView.as_view()), name='index'),
    path('crear/', login_required(CategoriaCreateView.as_view()), name='crear'),
    path('editar/<int:pk>/', login_required(CategoriaUpdateView.as_view()), name='editar'),
    path('eliminar/delete_ajax/', login_required(CategoriaDeleteAjax.as_view()), name='eliminar'),
]

core/categorias/models.py
from django.db import models
from django.db.models import Model

# Create your models here.

class Categoria(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=200)

    def __str__(self):
        return f'{self.nombre}: {self.descripcion}'

    def save(self, *args, **kwargs):
        if not self.id:
            count_cats = Categoria.objects.all().count()
            self.id = count_cats + 1
        super(Categoria, self).save(*args, **kwargs)

core/categorias/forms.py
from django.forms import ModelForm
from core.categorias.models import Categoria

class CategoriaForm(ModelForm):
    class Meta:
        model = Categoria
        fields = ['nombre', 'descripcion']

core/categorias/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView
from core.categorias.models import Categoria
from core.categorias.forms import CategoriaForm
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, JsonResponse

# Create your views here.

class CategoriaListView(ListView):
    model = Categoria
    template_name = 'categorias/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        context['user_group'] = str(user.groups.first())
        context['title'] = 'Categorías'
        return context


class CategoriaCreateView(CreateView):
    model = Categoria
    template_name = 'categorias/form.html'
    form_class = CategoriaForm
    success_url = reverse_lazy('categorias:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user = self.request.user
        context['user_group'] = str(user.groups.first())

        context['title'] = 'Nueva Categoria'
        context['back_url'] = self.success_url
        context['action'] = 'new'
        return context

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            form.save()
            # messages.success(request, 'La categoría se registró correctamente')
            return HttpResponseRedirect(self.success_url)

        messages.error(request, form.errors)
        return self.render_to_response(self.get_context_data(form=form))


class CategoriaUpdateView(UpdateView):
    model = Categoria
    template_name = 'categorias/form.html'
    form_class = CategoriaForm
    success_url = reverse_lazy('categorias:index')

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        context['user_group'] = str(user.groups.first())
        context['title'] = 'Modificar Categoria'
        context['back_url'] = self.success_url
        context['action'] = 'edit'
        return context

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            form.save()
            # messages.success(request, 'La categoría se modificó correctamente')
            return HttpResponseRedirect(self.success_url)

        messages.error(request, form.errors)
        return self.render_to_response(self.get_context_data(form=form))


class CategoriaDeleteAjax(TemplateView):

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            cat = Categoria.objects.get(pk=request.POST['id'])
            cat.delete()
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

templates/categorias/form.html
{% extends 'base/base_cards_form.html' %}

{% block contenido-nav %}
    <div class="col-sm-6">
        <h1 class="m-0 text-dark">Categoria - Registro</h1>
    </div><!-- /.col -->
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{% url 'base:index' %}">Inicio</a></li>
            <li class="breadcrumb-item"><a href="{% url 'categorias:index' %}">Categorias</a></li>
            <li class="breadcrumb-item active">Registro</li>
        </ol>
    </div><!-- /.col -->
{% endblock %}

{% block cardbody %}
    {% csrf_token %}
    {{ form.as_p|safe }}
{% endblock %}

templates/categorias/index.html
{% extends 'base/base_cards_list_datatable.html' %}

{% block contenido-nav %}
    <div class="col-sm-6">
        <h1 class="m-0 text-dark">Categorias</h1>
    </div><!-- /.col -->
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{% url 'base:index' %}">Inicio</a></li>
            <li class="breadcrumb-item active">Categorias</li>
        </ol>
    </div><!-- /.col -->

{% endblock %}

{% block tabla-columnas %}
    <th scope="col">#</th>
    <th scope="col" style="width: 30%;">Nombre</th>
    <th scope="col" style="width: 50%;">Descripcion</th>
    <th scope="col" style="width: 20%;">Acciones</th>
{% endblock %}

{% block tabla-body %}
    {% if object_list %}
        {% for cat in object_list %}
            <tr>
                <td>{{ cat.id }}</td>
                <td>{{ cat.nombre }}</td>
                <td>{{ cat.descripcion }}</td>
                <td style="text-align: center">
                    <!-- Boton Editar -->
                    <a class="btn btn-outline-warning btn-sm" style="margin-top: 1px;" data-toggle="tooltip"
                       data-placement="top"
                       title="" data-original-title="Editar la categoría {{ cat.id }}"
                       href="{% url 'categorias:editar' cat.id %}">
                        <i class="far fa-edit"></i>
                    </a>

                    <a class="btn btn-outline-danger btn-sm" style="margin-top: 1px;" data-toggle="tooltip"
                                   data-placement="top"
                                   title="" data-original-title="Eliminar la categoría {{ cat.id }}"
                                    onclick="Delete('{{ cat.id }}')"
                                   href="#">
                        <i class="fas fa-trash-alt"></i>
                    </a>
                </td>
            </tr>
        {% endfor %}
    {% endif %}
{% endblock %}

{% block js-datatable %}
    order: [ 1, 'asc' ],
    "columnDefs": [
    {"visible": false, "targets": 0}
    ], // ocultar columna ID
{% endblock %}

{% block js-list %}
    <script type="application/javascript">
        function Delete(id) {

            // Necesario para la seguridad del formulario
            var csrftoken = Cookies.get('csrftoken');

            function csrfSafeMethod(method) {
                // these HTTP methods do not require CSRF protection
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }

            $.ajaxSetup({
                beforeSend: function (xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });

            $.confirm({
                theme: 'material',
                title: '¡Cuidado!',
                icon: 'fa fa-exclamation-triangle',
                content: '¿Seguro que quiere ELIMINAR la categoría ' + id + ' ?',
                columnClass: 'medium',
                typeAnimated: true,
                cancelButtonClass: 'btn btn-secondary',
                draggable: true,
                dragWindowBorder: false,
                buttons: {
                    danger: {
                        text: "Si",
                        btnClass: 'btn btn-primary',
                        action: function () {

                            // función AJAX
                            $.ajax({
                                url: "{% url 'categorias:eliminar' %}",
                                type: "POST",
                                data: {'id': id},
                                dataType: "json",
                            }).done(function (data) {
                                if (!data.hasOwnProperty("error")) {
                                    alert_ok();
                                    return false;
                                }
                                alert_error(data.error);
                            }).fail(function (jqXHR, textStatus, errorThrown) {
                                alert_error(textStatus + ": " + errorThrown);
                            }).always(function (data) {
                                location.reload();
                            })
                        }
                    },
                    info: {
                        text: "No",
                        btnClass: 'btn btn-secondary',
                        action: function () {}
                    },
                }
            })

        }
    </script>
{% endblock %}